sudo: false
language: elixir
elixir:
  - 1.1.1
  - 1.2.6
  - 1.3.4
  - 1.4.4
otp_release:
  - 18.3
  - 19.3
script:
  - mix test && mix credo --mute-exit-status && mix credo lib/credo/sources.ex:1:11
after_script:
  - MIX_ENV=test mix inch.report
matrix:
  exclude:
  - elixir: 1.1.1
    otp_release: 19.3
