sudo: false
language: elixir
elixir:
  - 1.3.4
  - 1.4.5
  - 1.5.3
otp_release:
  - 18.3
  - 19.3
  - 20.0
script:
  - mix test
  - ./test/smoke_test.sh
after_script:
  - MIX_ENV=test mix inch.report
matrix:
  exclude:
  - elixir: 1.3.4
    otp_release: 20.0
