sudo: false
language: elixir
elixir:
  - 1.1.1
  - 1.2.6
  - 1.3.1
  - 1.4.0-rc.1
otp_release:
  - 18.0
  - 18.1
  - 18.2
  - 19.0
  - 19.1
script:
  - mix test && mix credo --mute-exit-status
after_script:
  - MIX_ENV=test mix inch.report
matrix:
  exclude:
  - elixir: 1.1.1
    otp_release: 19.0
  - elixir: 1.1.1
    otp_release: 19.1
