sudo: false
language: elixir
elixir:
  - 1.6.6
  - 1.7.2
  - 1.8.2
  - 1.9.4
otp_release:
  - 19.3
  - 20.3
  - 21.3
  - 22.0
script:
  - mix deps.compile
  - mix compile --warnings-as-errors
  - mix test
  - ./test/smoke_test.sh
after_script:
  - MIX_ENV=test mix inch.report
matrix:
  exclude:
  - elixir: 1.6.6
    otp_release: 22.0
  - elixir: 1.8.2
    otp_release: 19.3
  - elixir: 1.9.4
    otp_release: 19.3
