name: "CI Tests"
on:
  push:
    branches:
      - master
      - release/*
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    name: "[${{matrix.otp}}/${{matrix.elixir}}] CI Tests on Credo [OTP/Elixir]"
    strategy:
      fail-fast: false
      matrix:
        otp: [20.3, 21.3, 22.3, 23.3, 24.0]
        elixir: [1.8.2, 1.9.4, 1.10.4, 1.11.4, 1.12.2, 1.13.1]
        exclude:
          - otp: 24.0
            elixir: 1.8.2
          - otp: 24.0
            elixir: 1.9.4
          - otp: 24.0
            elixir: 1.10.4
          - otp: 23.3
            elixir: 1.8.2
          - otp: 23.3
            elixir: 1.9.4
          - otp: 21.3
            elixir: 1.12.2
          - otp: 20.3
            elixir: 1.10.4
          - otp: 20.3
            elixir: 1.11.4
          - otp: 20.3
            elixir: 1.12.2
          - otp: 20.3
            elixir: 1.13.1
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          fetch-depth: 0
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - run: mix deps.get
      - run: mix deps.compile
      - run: mix compile --warnings-as-errors
      - run: mix test.fast --include slow:disk_io
      - run: ./test/smoke_test.sh
