name: "Compatibility: Phoenix"
on:
  push:
    branches:
      - master
      - release/*

jobs:
  test_on_source:
    runs-on: ubuntu-18.04
    name: "[${{matrix.otp}}/${{matrix.elixir}}] Phoenix ${{matrix.repo_branch}} source code analysed by Credo [OTP/Elixir]"
    strategy:
      fail-fast: false
      matrix:
        otp: [21.3, 22.3, 23.3, 24.2]
        elixir: [1.10.4, 1.11.4, 1.12.2, 1.13.4, 1.14.0]
        exclude:
          - otp: 24.2
            elixir: 1.10.4
          - otp: 21.3
            elixir: 1.12.2
          - otp: 21.3
            elixir: 1.13.4
          - otp: 21.3
            elixir: 1.14.0
          - otp: 22.3
            elixir: 1.14.0
        repo_url: ["https://github.com/phoenixframework/phoenix.git"]
        repo_branch: ["v1.6", "master"]
    steps:
      - uses: actions/checkout@v2.3.1
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - run: mix deps.get
      - run: mix deps.compile
      - run: mix compile
      - run: mkdir -p tmp
      - run: git clone ${{matrix.repo_url}} tmp/${{matrix.repo_branch}} --depth=1 --branch ${{matrix.repo_branch}}
      - run: mix credo tmp/${{matrix.repo_branch}} --strict --mute-exit-status

  test_on_new_project:
    runs-on: ubuntu-latest
    name: "[${{matrix.otp}}/${{matrix.elixir}}] new Phoenix app analysed by Credo [OTP/Elixir]"
    strategy:
      matrix:
        otp: [21.3, 22.3, 23.3, 24.2]
        elixir: [1.10.4, 1.11.4, 1.12.2, 1.13.4, 1.14.0]
        exclude:
          - otp: 24.2
            elixir: 1.10.4
          - otp: 21.3
            elixir: 1.12.2
          - otp: 21.3
            elixir: 1.13.4
          - otp: 21.3
            elixir: 1.14.0
          - otp: 22.3
            elixir: 1.14.0
    steps:
      - uses: actions/checkout@v2.3.1
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - run: mix deps.get
      - run: mix deps.compile
      - run: mix compile
      - run: ./test/test_phoenix_compatibility.sh
