name: "Compatibility: Phoenix"
on:
  push:
    branches:
      - master

jobs:
  test_on_source:
    runs-on: ubuntu-latest
    name: "[${{matrix.otp}}/${{matrix.elixir}}] Phoenix ${{matrix.repo_branch}} source code analysed by Credo [OTP/Elixir]"
    strategy:
      matrix:
        otp: [20.3, 21.3, 22.2]
        elixir: [1.6.6, 1.7.2, 1.8.2, 1.9.4, 1.10.4]
        repo_url: ["https://github.com/phoenixframework/phoenix.git"]
        repo_branch: ["v1.4", "master"]
    steps:
      - uses: actions/checkout@v2.3.1
        if: "!(matrix.otp == '20.3' && matrix.elixir == '1.10.4')"
      - uses: actions/setup-elixir@v1.3
        if: "!(matrix.otp == '20.3' && matrix.elixir == '1.10.4')"
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}

      - run: mix deps.get
        if: "!(matrix.otp == '20.3' && matrix.elixir == '1.10.4')"

      - run: mix deps.compile
        if: "!(matrix.otp == '20.3' && matrix.elixir == '1.10.4')"

      - run: mix compile
        if: "!(matrix.otp == '20.3' && matrix.elixir == '1.10.4')"

      - run: mkdir -p tmp
        if: "!(matrix.otp == '20.3' && matrix.elixir == '1.10.4')"

      - run: git clone ${{matrix.repo_url}} tmp/${{matrix.repo_branch}} --depth=1 --branch ${{matrix.repo_branch}}
        if: "!(matrix.otp == '20.3' && matrix.elixir == '1.10.4')"

      - run: mix credo tmp/${{matrix.repo_branch}} --strict --mute-exit-status
        if: "!(matrix.otp == '20.3' && matrix.elixir == '1.10.4')"

  test_on_new_project:
    runs-on: ubuntu-latest
    name: "[${{matrix.otp}}/${{matrix.elixir}}] new Phoenix app analysed by Credo [OTP/Elixir]"
    strategy:
      matrix:
        otp: [20.3, 21.3, 22.2]
        elixir: [1.6.6, 1.7.2, 1.8.2, 1.9.4]
    steps:
      - uses: actions/checkout@v2.3.1
        if: "!(matrix.otp == '20.3' && matrix.elixir == '1.10.4')"
      - uses: actions/setup-elixir@v1.3
        if: "!(matrix.otp == '20.3' && matrix.elixir == '1.10.4')"
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}

      - run: mix deps.get
        if: "!(matrix.otp == '20.3' && matrix.elixir == '1.10.4')"

      - run: mix deps.compile
        if: "!(matrix.otp == '20.3' && matrix.elixir == '1.10.4')"

      - run: mix compile
        if: "!(matrix.otp == '20.3' && matrix.elixir == '1.10.4')"

      - run: ./test/test_phoenix_compatibility.sh
        if: "!(matrix.otp == '20.3' && matrix.elixir == '1.10.4')"
