name: "Compatibility: Elixir"
on:
  push:
    branches:
      - master
      - release/*

jobs:
  test_on_source:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"
    name: "[${{matrix.otp}}/${{matrix.elixir}}] Elixir ${{matrix.repo_branch}} source code analysed by Credo [OTP/Elixir]"
    strategy:
      fail-fast: false
      matrix:
        otp: [21.3, 22.3, 23.3, 24.2]
        elixir: [1.10.4, 1.11.4, 1.12.2, 1.13.4, 1.14.0]
        exclude:
          - otp: 24.0
            elixir: 1.10.4
          - otp: 21.3
            elixir: 1.12.2
          - otp: 21.3
            elixir: 1.13.4
          - otp: 21.3
            elixir: 1.14.0
        repo_url: ["https://github.com/elixir-lang/elixir.git"]
        repo_branch: ["v1.13", "main"]
    steps:
      - uses: actions/checkout@v2.3.1
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - run: mix deps.get
      - run: mix deps.compile
      - run: mix compile
      - run: mkdir -p tmp
      - run: git clone ${{matrix.repo_url}} tmp/${{matrix.repo_branch}} --depth=1 --branch ${{matrix.repo_branch}}
      - run: mix credo tmp/${{matrix.repo_branch}} --strict --mute-exit-status
